# Generated by Django 2.1 on 2018-08-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fairinfo',
            options={'verbose_name': 'Информация о ярмарке вакансий', 'verbose_name_plural': 'Информация о ярмарке вакансий'},
        ),
    ]
