# Generated by Django 2.1 on 2018-08-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name_plural': 'Медиа партнёры',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name_plural': 'Спонсоры',
            },
        ),
        migrations.AlterField(
            model_name='organizer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО или название'),
        ),
    ]
