# Generated by Django 2.1 on 2018-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20180901_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapartner',
            name='website',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='website',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='website',
        ),
        migrations.AddField(
            model_name='organizer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='logo_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
