# Generated by Django 2.1 on 2018-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20180901_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='ФИО или название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo_url', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Работодатели',
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('speaker', models.CharField(blank=True, max_length=255, null=True, verbose_name='Спикер')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
