# Generated by Django 2.1 on 2018-09-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20180911_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name_plural': 'Вид партнерства'},
        ),
    ]
