# Generated by Django 2.1 on 2018-09-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20180911_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fairinfo',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='fairinfo',
            name='target',
        ),
        migrations.RemoveField(
            model_name='fairinfo',
            name='task',
        ),
    ]
