# Generated by Django 2.1 on 2018-09-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20180911_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytype',
            name='type_name',
            field=models.CharField(max_length=100, verbose_name='Вид партнерства'),
        ),
    ]
